### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by AlanHolmes** [FabianBeiner/Todoist-PHP-API-Library#2]
Hi

From the [API docs](https://developer.todoist.com/rest/v8/#close-a-task) the close task and reopen task methods are expecting a post method, but the get method is being used instead, so it is returning a 405 Method Not Allowed error.

I am putting together a quick pull request for this as well.

Regards
Alan

**Comment by AlanHolmes** [comment]
Well, I have tried to submit a pull request, but I do not have permission.

Changes where just in the `TodoistTasksTrait` trait, for the `closeTask` and `reopenTask` methods from 

```php
// closeTask
$result = $this->get('tasks/' . $taskId . '/close');
// reopenTask
$result = $this->get('tasks/' . $taskId . '/repoen');
```

to

```php
// closeTask
$result = $this->post('tasks/' . $taskId . '/close');
// reopenTask
$result = $this->post('tasks/' . $taskId . '/repoen');
```

**Comment by FabianBeiner** [comment]
Hi @AlanHolmes,

Thanks for pointing this out! I'm pretty sure this was working, so Todoist most likely changed that. But since there is no change log, I can't track what's changing.

I'll push a new version soon.

> Well, I have tried to submit a pull request, but I do not have permission.

You tried to push the changes to my repository directly, am I right? This is not how it works here. Read more about pull requests here: https://help.github.com/articles/about-pull-requests/

Cheers,
Fabian

**Comment by AlanHolmes** [comment]
Hi @FabianBeiner 

I guess you use the Fork method, my bad, I'm used to just creating a branch and a PR from that.

Thanks for making the change, however, it won't pull down during my composer update, as there is no tag for the 0.7.1 version.

Cheers,
Alan

**Comment by FabianBeiner** [comment]
Sorry, forgot that! Tag is available now.
