### ISSUE TITLE
Sync API plans?

### ISSUE THREAD

**Issue by wizonesolutions** [FabianBeiner/Todoist-PHP-API-Library#4]
Wondering if you are planning to implement any Sync API endpoints here. e.g. when creating a project with the REST API, one can't set the indent, etc., so subprojects are basically impossible. I assume Todoist will improve the REST API before they release it, but was just curious.

**Comment by FabianBeiner** [comment]
First of all, I wouldn't mix those two. So it's either the REST API or the Sync API. I chose the first one, because it's much more simple for the end user because you don't have to fiddle around with OAuth and all that stuff.

I created this PHP client, because I love Todoist, and I am using it for ages. But: I myself don't have any need for this library nor any other. ;-) I created it for fun. The minute I need it and run into any limitations, I'll probably start with the Sync API version.

**Comment by wizonesolutions** [comment]
Haha, yeah, I totally understand—they are quite different. Todoist keeps getting better and better. I'm going to see if I can get them to sponsor a Sync API. It is possible to use personal tokens with the Sync API as well, actually (I think). They just don't make it as obvious. It's way more robust. I'm making a tool to import a CSV from the 2Do app into Todoist via the REST API, but it's so limited...not even repeating dates. It's still good enough for me; it just got me thinking.

**Comment by FabianBeiner** [comment]
While I love Todoist, I think that Doist doesn't really care about the API or the users that much. There isn't even a changelog available yet, which makes it really hard to rely on the API, because basically everything could be breaking changes.

Anyway: Don't those `due_*` options from the REST API work for you?

**Comment by wizonesolutions** [comment]
@FabianBeiner Hmm, I don't think one can set recurrence with the `due_*` options, though. The API doesn't seem to use the same parsing as the UI :(

I noticed the REST API also breaks after too many requests in a row, so there is some secret, unpublished rate limit (like 15-30 seconds or so after it starts failing).

My impression is that the Sync API is the real API, and the beta REST API is still very...beta.
